Separate tasks calendars in list
elementary/switchboard-plug-onlineaccounts pull request #165
Opened 2021-05-26 19:34 UTC by marbetschar

Separates Task and Calendars in the list view of the CalDAV dialog.

2021-05-26 21:40 UTC, danrabbit requested changes
I'm no longer getting sources sorted in alphabetical order here, which is not a huge deal, but it could be fixed by using `insert_sorted` as in https://github.com/elementary/code/blob/master/src/Services/GitManager.vala#L47

One inline comment about the header func

2021-05-26 21:40 UTC, danrabbit commented on src/Dialogs/CaldavDialog.vala
> +            }
Because you are adding calendars to the liststore and then adding tasklists, this seems like an impossible case

2021-05-27 07:42 UTC, marbetschar commented
@danrabbit re-added `sort_func` and improved it a bit. Looks good now on my end. Can you please re-review?

2021-05-27 16:41 UTC, danrabbit approved these changes
LFG

2021-05-27 16:41 UTC, merged