Verify E-Mail Credentials
elementary/switchboard-plug-onlineaccounts pull request #189
Opened 2021-07-09 11:45 UTC by marbetschar

This PR adds E-Mail credential verification to the configuration dialog.

While the basic UI logic is in place, the actual verification does not work yet.

2021-07-12 10:56 UTC, marbetschar commented
Although the current codebase works for Office 365 verification I always get a `IMAP: Too many commands before auth` for Gmail and Yandex plain simply hangs during IMAP validation and then runs into the timeout.

@tintou or @davidmhewitt any ideas what I'm missing here?

2021-07-21 21:43 UTC, marbetschar commented
@danrabbit any chance you can give this code a test run for Gmail configuration account?

I always get a `IMAP server said: BYE: Too many commands before auth` for Gmail - all other mail accounts do work just fine on my end.

2021-07-23 08:41 UTC, marbetschar commented
Turned out EDS is already fully capable to figure out paths to well known folders: Its [`imapx_initial_setup_sync`](https://gitlab.gnome.org/GNOME/evolution-data-server/-/blob/master/src/camel/providers/imapx/camel-imapx-store.c#L2733) does exactly what we want. Added to this PR because we need a `Camel.Store` for it.

[This change](https://github.com/elementary/switchboard-plug-onlineaccounts/pull/189/commits/2f01c0f1bc54920fa7ec52b261ca4fa2275c0468) also adds support for Well Known Folders on Office 365, which did not work with the previous implementation.

2021-07-23 16:32 UTC, danrabbit requested changes
Hey right on! I can confirm that this errors out with bad credentials and succeeds with good ones.

Nice to know there's an upstream method for getting the special folders! It seems like this isn't as good at detecting all the Gmail folders, but we can pursue that upstream

Just a couple of small changes and I think we're good to go. Thanks for working on this! Way better setup experience

2021-07-23 16:32 UTC, danrabbit commented on src/Dialogs/Imap/ImapSavePage.vala
> +            _("Unable to add mail account."),
It looks like we always set the error description to whatever is passed in via `show_error`, so we should probably leave the description empty and use this string here for the title:
```suggestion
            _("Unable to add mail account"),
            ""
```

2021-07-23 16:32 UTC, danrabbit commented on src/Dialogs/Imap/ImapDialog.vala
> +                "IMAP verification failed: %s".printf (e.message)
since this is a string we show users on error we should translate it

2021-07-23 16:32 UTC, danrabbit commented on src/Dialogs/Imap/ImapDialog.vala
> +                    "Can't login. Please verify your credentials."
Same here, we should make sure to translate these error descriptions

2021-07-23 16:32 UTC, danrabbit commented on src/Dialogs/Imap/ImapSavePage.vala
> +    public void show_success () {
should we make the button button insensitive here probably?

2021-07-23 23:39 UTC, danrabbit approved these changes
Fantastic work as always!

2021-07-23 23:39 UTC, merged