Allow to configure the interval in minutes to fetch new email
elementary/switchboard-plug-onlineaccounts pull request #238
Opened 2022-01-08 15:12 UTC by kalmbach

ref elementary/switchboard-plug-onlineaccounts#223

2022-01-08 16:10 UTC, meisenzahl requested changes
The code looks good so far, just a bit nitpicking 🤓

2022-01-08 16:10 UTC, meisenzahl commented on po/online-accounts-plug.pot
> +"POT-Creation-Date: 2022-01-08 11:17-0300\n"
Please reset the changes to this file. The translation files are handled by [Weblate](https://l10n.elementary.io/projects/switchboard/switchboard-plug-onlineaccounts/).

2022-01-08 16:10 UTC, meisenzahl commented on src/Dialogs/Imap/ImapDialog.vala
> +        imap_refresh_interval_spin = new Gtk.SpinButton.with_range(1, 60, 1) {
```suggestion
        imap_refresh_interval_spin = new Gtk.SpinButton.with_range (1, 60, 1) {
```

We insert white space before opening parentheses or braces.

Reference
- https://docs.elementary.io/develop/writing-apps/code-style#whitespace

2022-01-08 16:26 UTC, meisenzahl commented
@kalmbach thanks for implementing my comments so quickly. Is it also possible to change the interval for an already configured account in edit mode?

![Bildschirmfoto von 2022-01-08 17 25 32](https://user-images.githubusercontent.com/10796736/148651834-04858c7f-94fd-4870-bb2d-35d8566db63b.png)

2022-01-08 16:28 UTC, kalmbach commented
Thanks for the review @meisenzahl !!

2022-01-08 16:30 UTC, kalmbach commented
> @kalmbach thanks for implementing my comments so quickly. Is it also possible to change the interval for an already configured account in edit mode?

@meisenzahl yarp! It is.

2022-01-08 17:14 UTC, meisenzahl commented
@kalmbach nice! Let's wait for some input of @elementary/ux.

2022-01-08 17:14 UTC, meisenzahl approved these changes

2022-01-11 20:17 UTC, danrabbit approved these changes
Nice work!

2022-01-11 20:18 UTC, merged