ImapDialog: use Adw.NavigationView
elementary/switchboard-plug-onlineaccounts pull request #283
Opened 2024-06-19 20:04 UTC by danirabbit

Replaces deprecated Leaflet

2024-06-23 14:32 UTC, leolost2605 requested changes

2024-06-23 14:32 UTC, leolost2605 commented on src/Dialogs/Imap/ImapDialog.vala
> +            navigation_view.pop ();
Another mem leak :(
(At least if back_buttons' life time depends on us, I'm not to deep in the codebase)

2024-06-23 14:32 UTC, leolost2605 commented on src/Dialogs/Imap/ImapDialog.vala
> +            navigation_view.pop ();
Mem leak if save_page lifetime depends on us (I'm not sure if it does since I'm not to deep in the codebase)

2024-06-23 14:32 UTC, leolost2605 commented on src/Dialogs/Imap/ImapDialog.vala
> +            navigation_view.push (main_page);
Mem leak if login_page.next_button lifetime depends on us

2024-06-23 14:34 UTC, leolost2605 commented
I've left some comments about possible mem leaks. Because this is not a continually running process mem leaks aren't that bad here but I think we should kinda get aware of them because e.g. in dock we probably have quite a bunch since it starts with 200mb and after an hour or two of normal use it has 800mb :(

2024-06-28 18:16 UTC, danirabbit commented
@leolost2605 How's that? :)

2024-07-01 16:42 UTC, leolost2605 requested changes
Still not quite perfect I left a few comments.
I'm still trying to write a somewhat good explanation but for a start I left some more info here https://github.com/elementary/terminal/pull/760#issuecomment-2186547930. 
To test it you can add a destructor and put a warning in it to see if it gets destroyed on close. Note though that on master it also doesn't get destroyed currently and only if you comment out a lot of the signal connections so for this class this might not be the best test. 
To see whether the things you touched are problematic you can open the c file and make sure the lambdas that are handling signals that you worked on are connected with  `g_signal_connect_object` and not `g_signal_connect_full`. 
Kinda annoying I know :/

2024-07-01 16:42 UTC, leolost2605 commented on src/Dialogs/Imap/ImapDialog.vala
> +            push_page (main_page);
AFAICT main_page will never be removed so its lifetime depends on `this` creating the ref cycle. To get around this you could just add a private Adw.NavigationPage main_page for it.

2024-07-01 16:42 UTC, leolost2605 commented on src/Dialogs/Imap/ImapDialog.vala
> +    private void push_page (Adw.NavigationPage page) {
That's not really necessary the only important thing is that navigation_view isn't a local variable. So by not using lambdas you kinda force yourself to not use local variables but lambdas aren't the actual source of the problem.

2024-07-02 17:37 UTC, danirabbit commented
@leolost2605 okay how's this? I don't see any signal_connect_full in the generated C

2024-07-02 17:44 UTC, leolost2605 commented
Sorry I typed it on my phone without checking, it should have been `g_signal_connect_data` 😖

2024-07-02 17:53 UTC, danirabbit commented
@leolost2605 it looks like there was only one of those so I went ahead of fixed it even though it's not related to this branch :)

2024-07-03 14:44 UTC, leolost2605 approved these changes
Nice!

2024-07-03 15:57 UTC, merged